{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "55917798-e62b-42b9-9332-c0bb543682d5",
   "metadata": {},
   "outputs": [],
   "source": [
    "from enum import Enum\n",
    "\n",
    "\n",
    "class Location(Enum):\n",
    "    HOME = \"HOME\"\n",
    "    AWAY = \"AWAY\"\n",
    "\n",
    "\n",
    "class Outcome(Enum):\n",
    "    WIN = \"WIN\"\n",
    "    LOSS = \"LOSS\"\n",
    "\n",
    "\n",
    "class Team(Enum):\n",
    "    ATLANTA_HAWKS = \"ATLANTA HAWKS\"\n",
    "    BOSTON_CELTICS = \"BOSTON CELTICS\"\n",
    "    BROOKLYN_NETS = \"BROOKLYN NETS\"\n",
    "    CHARLOTTE_HORNETS = \"CHARLOTTE HORNETS\"\n",
    "    CHICAGO_BULLS = \"CHICAGO BULLS\"\n",
    "    CLEVELAND_CAVALIERS = \"CLEVELAND CAVALIERS\"\n",
    "    DALLAS_MAVERICKS = \"DALLAS MAVERICKS\"\n",
    "    DENVER_NUGGETS = \"DENVER NUGGETS\"\n",
    "    DETROIT_PISTONS = \"DETROIT PISTONS\"\n",
    "    GOLDEN_STATE_WARRIORS = \"GOLDEN STATE WARRIORS\"\n",
    "    HOUSTON_ROCKETS = \"HOUSTON ROCKETS\"\n",
    "    INDIANA_PACERS = \"INDIANA PACERS\"\n",
    "    LOS_ANGELES_CLIPPERS = \"LOS ANGELES CLIPPERS\"\n",
    "    LOS_ANGELES_LAKERS = \"LOS ANGELES LAKERS\"\n",
    "    MEMPHIS_GRIZZLIES = \"MEMPHIS GRIZZLIES\"\n",
    "    MIAMI_HEAT = \"MIAMI HEAT\"\n",
    "    MILWAUKEE_BUCKS = \"MILWAUKEE BUCKS\"\n",
    "    MINNESOTA_TIMBERWOLVES = \"MINNESOTA TIMBERWOLVES\"\n",
    "    NEW_ORLEANS_PELICANS = \"NEW ORLEANS PELICANS\"\n",
    "    NEW_YORK_KNICKS = \"NEW YORK KNICKS\"\n",
    "    OKLAHOMA_CITY_THUNDER = \"OKLAHOMA CITY THUNDER\"\n",
    "    ORLANDO_MAGIC = \"ORLANDO MAGIC\"\n",
    "    PHILADELPHIA_76ERS = \"PHILADELPHIA 76ERS\"\n",
    "    PHOENIX_SUNS = \"PHOENIX SUNS\"\n",
    "    PORTLAND_TRAIL_BLAZERS = \"PORTLAND TRAIL BLAZERS\"\n",
    "    SACRAMENTO_KINGS = \"SACRAMENTO KINGS\"\n",
    "    SAN_ANTONIO_SPURS = \"SAN ANTONIO SPURS\"\n",
    "    TORONTO_RAPTORS = \"TORONTO RAPTORS\"\n",
    "    UTAH_JAZZ = \"UTAH JAZZ\"\n",
    "    WASHINGTON_WIZARDS = \"WASHINGTON WIZARDS\"\n",
    "\n",
    "    # DEPRECATED TEAMS\n",
    "    CHARLOTTE_BOBCATS = \"CHARLOTTE BOBCATS\"\n",
    "    NEW_JERSEY_NETS = \"NEW JERSEY NETS\"\n",
    "    NEW_ORLEANS_HORNETS = \"NEW ORLEANS HORNETS\"\n",
    "    NEW_ORLEANS_OKLAHOMA_CITY_HORNETS = \"NEW ORLEANS/OKLAHOMA CITY HORNETS\"\n",
    "    SEATTLE_SUPERSONICS = \"SEATTLE SUPERSONICS\"\n",
    "    VANCOUVER_GRIZZLIES = \"VANCOUVER GRIZZLIES\"\n",
    "\n",
    "\n",
    "class OutputType(Enum):\n",
    "    JSON = \"JSON\"\n",
    "    CSV = \"CSV\"\n",
    "\n",
    "\n",
    "class OutputWriteOption(Enum):\n",
    "    WRITE = \"w\"\n",
    "    CREATE_AND_WRITE = \"w+\"\n",
    "    APPEND = \"a\"\n",
    "    APPEND_AND_WRITE = \"a+\"\n",
    "\n",
    "\n",
    "class Position(Enum):\n",
    "    POINT_GUARD = \"POINT GUARD\"\n",
    "    SHOOTING_GUARD = \"SHOOTING GUARD\"\n",
    "    SMALL_FORWARD = \"SMALL FORWARD\"\n",
    "    POWER_FORWARD = \"POWER FORWARD\"\n",
    "    CENTER = \"CENTER\"\n",
    "\n",
    "\n",
    "TEAM_ABBREVIATIONS_TO_TEAM = {\n",
    "    'ATL': Team.ATLANTA_HAWKS,\n",
    "    'BOS': Team.BOSTON_CELTICS,\n",
    "    'BRK': Team.BROOKLYN_NETS,\n",
    "    'CHI': Team.CHICAGO_BULLS,\n",
    "    'CHO': Team.CHARLOTTE_HORNETS,\n",
    "    'CLE': Team.CLEVELAND_CAVALIERS,\n",
    "    'DAL': Team.DALLAS_MAVERICKS,\n",
    "    'DEN': Team.DENVER_NUGGETS,\n",
    "    'DET': Team.DETROIT_PISTONS,\n",
    "    'GSW': Team.GOLDEN_STATE_WARRIORS,\n",
    "    'HOU': Team.HOUSTON_ROCKETS,\n",
    "    'IND': Team.INDIANA_PACERS,\n",
    "    'LAC': Team.LOS_ANGELES_CLIPPERS,\n",
    "    'LAL': Team.LOS_ANGELES_LAKERS,\n",
    "    'MEM': Team.MEMPHIS_GRIZZLIES,\n",
    "    'MIA': Team.MIAMI_HEAT,\n",
    "    'MIL': Team.MILWAUKEE_BUCKS,\n",
    "    'MIN': Team.MINNESOTA_TIMBERWOLVES,\n",
    "    'NOP': Team.NEW_ORLEANS_PELICANS,\n",
    "    'NYK': Team.NEW_YORK_KNICKS,\n",
    "    'OKC': Team.OKLAHOMA_CITY_THUNDER,\n",
    "    'ORL': Team.ORLANDO_MAGIC,\n",
    "    'PHI': Team.PHILADELPHIA_76ERS,\n",
    "    'PHO': Team.PHOENIX_SUNS,\n",
    "    'POR': Team.PORTLAND_TRAIL_BLAZERS,\n",
    "    'SAC': Team.SACRAMENTO_KINGS,\n",
    "    'SAS': Team.SAN_ANTONIO_SPURS,\n",
    "    'TOR': Team.TORONTO_RAPTORS,\n",
    "    'UTA': Team.UTAH_JAZZ,\n",
    "    'WAS': Team.WASHINGTON_WIZARDS,\n",
    "\n",
    "    # DEPRECATED TEAMS\n",
    "    'NJN': Team.NEW_JERSEY_NETS,\n",
    "    'NOH': Team.NEW_ORLEANS_HORNETS,\n",
    "    'NOK': Team.NEW_ORLEANS_OKLAHOMA_CITY_HORNETS,\n",
    "    'CHA': Team.CHARLOTTE_BOBCATS,\n",
    "    'CHH': Team.CHARLOTTE_HORNETS,\n",
    "    'SEA': Team.SEATTLE_SUPERSONICS,\n",
    "    'VAN': Team.VANCOUVER_GRIZZLIES,\n",
    "}\n",
    "\n",
    "POSITION_ABBREVIATIONS_TO_POSITION = {\n",
    "    \"PG\": Position.POINT_GUARD,\n",
    "    \"SG\": Position.SHOOTING_GUARD,\n",
    "    \"SF\": Position.SMALL_FORWARD,\n",
    "    \"PF\": Position.POWER_FORWARD,\n",
    "    \"C\": Position.CENTER,\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "cdbba932-3bca-4bf0-8a57-2c04242a49f0",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
