{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "a5add123-b118-41de-842a-6ceb728b1448",
   "metadata": {},
   "outputs": [
    {
     "ename": "ImportError",
     "evalue": "cannot import name 'basicOrAdvancedStatZScore' from 'standardizeStats' (/Users/JakeDoherty_1/Desktop/BOOTCAMP/Project 2 folder/standardizeStats.py)",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mImportError\u001b[0m                               Traceback (most recent call last)",
      "\u001b[0;32m/var/folders/pb/9nrds4y576x41j1jw01gnkc40000gn/T/ipykernel_2342/1177943486.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0;31m# May need to edit which lines are commented out based on what range of game data you would like to use\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 5\u001b[0;31m \u001b[0;32mfrom\u001b[0m \u001b[0mstandardizeStats\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mbasicOrAdvancedStatZScore\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mbasicOrAdvancedStatStandardDeviation\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mbasicOrAdvancedStatMean\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      6\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0mgetDailyMatchups\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mdailyMatchupsPast\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      7\u001b[0m \u001b[0;32mfrom\u001b[0m \u001b[0mgetStats\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mgetStatsForTeam\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mImportError\u001b[0m: cannot import name 'basicOrAdvancedStatZScore' from 'standardizeStats' (/Users/JakeDoherty_1/Desktop/BOOTCAMP/Project 2 folder/standardizeStats.py)"
     ]
    }
   ],
   "source": [
    "# createModel.py - Used to train, test, and create the model\n",
    "# Call createModel() to generate a new model\n",
    "# May need to edit which lines are commented out based on what range of game data you would like to use\n",
    "\n",
    "from standardizeStats import basicOrAdvancedStatZScore, basicOrAdvancedStatStandardDeviation, basicOrAdvancedStatMean\n",
    "from getDailyMatchups import dailyMatchupsPast\n",
    "from getStats import getStatsForTeam\n",
    "from availableStats import availableStats\n",
    "from configureCWD import setCurrentWorkingDirectory\n",
    "\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "from sklearn import metrics\n",
    "import pandas as pd\n",
    "import pickle\n",
    "\n",
    "from datetime import timedelta, date\n",
    "\n",
    "\n",
    "# Calculates the zScore differential between two teams for a specified stat\n",
    "def zScoreDifferential(observedStatHome, observedStatAway, mean, standardDeviation):\n",
    "\n",
    "    homeTeamZScore = basicOrAdvancedStatZScore(observedStatHome, mean, standardDeviation)\n",
    "    awayTeamZScore = basicOrAdvancedStatZScore(observedStatAway, mean, standardDeviation)\n",
    "\n",
    "    differenceInZScore = homeTeamZScore - awayTeamZScore\n",
    "    return differenceInZScore\n",
    "\n",
    "\n",
    "# Used to combine and format all the data to be put into a pandas dataframe\n",
    "# dailyGames should be list where index 0 is a dictionary holding the games and index 1 is a list holding the results\n",
    "def infoToDataFrame(dailyGames, meanDict, standardDeviationDict, startDate, endDate, season):\n",
    "\n",
    "    fullDataFrame = []\n",
    "    gameNumber = 0  # Counter to match the result of the game with the correct game\n",
    "    dailyResults = dailyGames[1]  # List of results for the games\n",
    "\n",
    "    for homeTeam,awayTeam in dailyGames[0].items():\n",
    "\n",
    "        homeTeamStats = getStatsForTeam(homeTeam, startDate, endDate, season)\n",
    "        awayTeamStats = getStatsForTeam(awayTeam, startDate, endDate, season)\n",
    "\n",
    "        currentGame = [homeTeam,awayTeam]\n",
    "\n",
    "        for stat,statType in availableStats.items():  # Finds Z Score Dif for stats listed above and adds them to list\n",
    "            zScoreDif = zScoreDifferential(homeTeamStats[stat], awayTeamStats[stat], meanDict[stat], standardDeviationDict[stat])\n",
    "            currentGame.append(zScoreDif)\n",
    "\n",
    "        if dailyResults[gameNumber] == 'W':  # Sets result to 1 if a win\n",
    "            result = 1\n",
    "        else:  # Sets result to 0 if loss\n",
    "            result = 0\n",
    "\n",
    "        currentGame.append(result)\n",
    "        gameNumber += 1\n",
    "\n",
    "        print(currentGame)\n",
    "        fullDataFrame.append(currentGame)  # Adds this list to list of all games on specified date\n",
    "\n",
    "    return(fullDataFrame)\n",
    "\n",
    "\n",
    "# Function that allows iterating through specified start date to end date\n",
    "def daterange(startDate, endDate):\n",
    "\n",
    "    for n in range(int ((endDate - startDate).days)):\n",
    "        yield startDate + timedelta(n)\n",
    "\n",
    "\n",
    "# Returns a list. Index 0 is a dict holding mean for each stat. Index 1 is a dict holding standard deviation for each stat.\n",
    "def createMeanStandardDeviationDicts(startDate, endDate, season):\n",
    "\n",
    "    meanDict = {}\n",
    "    standardDeviationDict = {}\n",
    "\n",
    "    # Loops through and inputs standard deviation and mean for each stat into dict\n",
    "    for stat, statType in availableStats.items():\n",
    "        statMean = basicOrAdvancedStatMean(startDate, endDate, stat, statType, season)\n",
    "        meanDict.update({stat: statMean})\n",
    "\n",
    "        statStandardDeviation = basicOrAdvancedStatStandardDeviation(startDate, endDate, stat, statType, season)\n",
    "        standardDeviationDict.update({stat: statStandardDeviation})\n",
    "\n",
    "    bothDicts = []\n",
    "    bothDicts.append(meanDict)\n",
    "    bothDicts.append(standardDeviationDict)\n",
    "\n",
    "    return bothDicts\n",
    "\n",
    "\n",
    "# Loops through every date between start and end and appends each game to a singular list to be returned\n",
    "# season should be in format 'yyyy-yy' and startOfSeason should be in format 'mm/dd/yyyy'\n",
    "def getTrainingSet(startYear, startMonth, startDay, endYear, endMonth, endDay, season, startOfSeason):\n",
    "\n",
    "    startDate = date(startYear, startMonth, startDay)\n",
    "    endDate = date(endYear, endMonth, endDay)\n",
    "\n",
    "    startDateFormatted = startDate.strftime(\"%m/%d/%Y\")  # Formats start date in mm/dd/yyyy\n",
    "    allGames = []\n",
    "\n",
    "    for singleDate in daterange(startDate, endDate):\n",
    "        currentDate = singleDate.strftime(\"%m/%d/%Y\")  # Formats current date in mm/dd/yyyy\n",
    "        print(currentDate)\n",
    "\n",
    "        previousDay = singleDate - timedelta(days=1)\n",
    "        previousDayFormatted = previousDay.strftime(\"%m/%d/%Y\")\n",
    "\n",
    "        meanAndStandardDeviationDicts = createMeanStandardDeviationDicts(startOfSeason, previousDayFormatted, season)\n",
    "        meanDict = meanAndStandardDeviationDicts[0]  # Dict in format {stat:statMean}\n",
    "        standardDeviationDict = meanAndStandardDeviationDicts[1]  # Dict in format {stat:statStDev}\n",
    "\n",
    "        currentDayGames = dailyMatchupsPast(currentDate, season)  # Finds games on current date in loop\n",
    "        currentDayGamesAndStatsList = infoToDataFrame(currentDayGames, meanDict, standardDeviationDict, startOfSeason, previousDayFormatted, season)  # Formats Z Score difs for games on current date in loop\n",
    "\n",
    "        for game in currentDayGamesAndStatsList:  # Adds game with stats to list of all games\n",
    "            game.append(currentDate)\n",
    "            allGames.append(game)\n",
    "\n",
    "    print(allGames)\n",
    "    return(allGames)\n",
    "\n",
    "\n",
    "# Returns a dataframe from list of games with z score differentials\n",
    "def createDataFrame(listOfGames):\n",
    "\n",
    "    games = pd.DataFrame(\n",
    "        listOfGames,\n",
    "        columns=['Home', 'Away', 'W_PCT', 'REB', 'TOV', 'PLUS_MINUS', 'OFF_RATING', 'DEF_RATING', 'TS_PCT', 'Result', 'Date']\n",
    "    )\n",
    "\n",
    "    print(games)\n",
    "    return(games)\n",
    "\n",
    "\n",
    "# Creates the logistic regression model and tests accuracy\n",
    "def performLogReg(dataframe):\n",
    "\n",
    "    # Update if new stats are added\n",
    "    featureColumns = ['W_PCT', 'REB', 'TOV', 'PLUS_MINUS', 'OFF_RATING', 'DEF_RATING', 'TS_PCT']\n",
    "\n",
    "    X = dataframe[featureColumns] # Features\n",
    "    Y = dataframe.Result  # Target Variable\n",
    "\n",
    "    X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.25, shuffle=True)\n",
    "    logreg = LogisticRegression()\n",
    "\n",
    "    logreg.fit(X_train, Y_train)  # Fits model with data\n",
    "\n",
    "    Y_pred = logreg.predict(X_test)\n",
    "\n",
    "    confusionMatrix = metrics.confusion_matrix(Y_test, Y_pred)  # Diagonals tell you correct predictions\n",
    "\n",
    "    # Code below prints model accuracy information\n",
    "    print('Coefficient Information:')\n",
    "\n",
    "    for i in range(len(featureColumns)):  # Prints each feature next to its corresponding coefficient in the model\n",
    "\n",
    "        logregCoefficients = logreg.coef_\n",
    "\n",
    "        currentFeature = featureColumns[i]\n",
    "        currentCoefficient = logregCoefficients[0][i]\n",
    "\n",
    "        print(currentFeature + ': ' + str(currentCoefficient))\n",
    "\n",
    "    print('----------------------------------')\n",
    "\n",
    "    print(\"Accuracy:\", metrics.accuracy_score(Y_test, Y_pred))\n",
    "    print(\"Precision:\", metrics.precision_score(Y_test, Y_pred))\n",
    "    print(\"Recall:\", metrics.recall_score(Y_test, Y_pred))\n",
    "\n",
    "    print('----------------------------------')\n",
    "\n",
    "    print('Confusion Matrix:')\n",
    "    print(confusionMatrix)\n",
    "\n",
    "    return logreg\n",
    "\n",
    "\n",
    "# Saves the model in folder to be used in future\n",
    "# filename should be end in '.pkl'\n",
    "def saveModel(model, filename):\n",
    "\n",
    "    # Change to where you want to save the model\n",
    "    setCurrentWorkingDirectory('SavedModels')\n",
    "\n",
    "    with open(filename, 'wb') as file:\n",
    "        pickle.dump(model, file)\n",
    "\n",
    "\n",
    "# Used to generate new logistic regression models\n",
    "# Can import the statistics and predictions for each game from a csv file or can be created on their own\n",
    "def createModel(startYear=None, startMonth=None, startDay=None, endYear=None, endMonth=None, endDay=None, season='2018-19', startOfSeason = '10/16/2018', filename='model.pkl'):\n",
    "\n",
    "    # allGames = getTrainingSet(startYear, startMonth, startDay, endYear, endMonth, endDay, season, startOfSeason)  # Unnecessary if using data from CSV file\n",
    "\n",
    "    # allGamesDataframe = createDataFrame(allGames)  # Unnecessary if using data from CSV file\n",
    "\n",
    "    setCurrentWorkingDirectory('Data')\n",
    "    allGamesDataframe = pd.read_csv('COMBINEDgamesWithInfo2016-19.csv')  # Should be commented out if needing to obtain data on different range of games\n",
    "\n",
    "    logRegModel = performLogReg(allGamesDataframe)\n",
    "\n",
    "    saveModel(logRegModel, filename)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c1e9fd5e-5c3f-492d-bbf0-f95e55f6f35b",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
